#!/usr/bin/env bash
#
# Parallar demo — a verifiable settlement layer on Stellar.
#
# Fresh-clone, one command. Walks the full scenario the way the system actually runs it,
# proving each beat with real code: a type registered and TWO instruments factory-deployed,
# deposits + Poseidon-committed cover, an epoch that is fully paid (for which NO settlement
# proof can exist), a partial default, a REAL Groth16 proof, that proof VERIFIED ON-CHAIN by
# the real RISC Zero verifier, confidential payouts through the vault, and forged/replay/
# stale-root attempts reverting — then benchmarks.
#
# It does NOT require testnet keys or a 34-minute live proof: it uses the committed real-proof
# fixture (prover/host/tests/fixtures/real_proof.json, generated by the proving spike) and the
# in-process Soroban host. To prove live + submit to testnet, see the "Going live" note at the
# end (parallar-prover prove | submit).
set -euo pipefail

cd "$(dirname "$0")"
export PATH="$HOME/.risc0/bin:$HOME/.cargo/bin:/opt/homebrew/bin:$PATH"

bold=$(tput bold 2>/dev/null || true); dim=$(tput dim 2>/dev/null || true)
grn=$(tput setaf 2 2>/dev/null || true); cyn=$(tput setaf 6 2>/dev/null || true)
ylw=$(tput setaf 3 2>/dev/null || true); rst=$(tput sgr0 2>/dev/null || true)

step=0
beat() { step=$((step+1)); printf "\n${bold}${cyn}━━ %d. %s${rst}\n" "$step" "$1"; [ $# -gt 1 ] && printf "${dim}   %s${rst}\n" "$2" || true; }
note() { printf "${dim}   %s${rst}\n" "$1"; }
ok()   { printf "${grn}   ✓ %s${rst}\n" "$1"; }

# run a cargo test filter quietly; print ✓ with the pass count, fail loudly
run() { # run <label> <manifest> <pkg> <filter...>
  local label="$1" manifest="$2" pkg="$3"; shift 3
  local out; out=$(cargo test --manifest-path "$manifest" -p "$pkg" "$@" 2>&1) || { echo "$out"; echo "${ylw}demo FAILED at: $label${rst}"; exit 1; }
  local res; res=$(echo "$out" | grep -Eo '[0-9]+ passed' | head -1 || echo "ok")
  ok "$label  (${res})"
}

printf "${bold}${cyn}\n"
printf "  ╔══════════════════════════════════════════════════════════════╗\n"
printf "  ║   PARALLAR — verifiable settlement on Stellar (demo)          ║\n"
printf "  ╚══════════════════════════════════════════════════════════════╝${rst}\n"
note "Determination off-chain · positions confidential · settlement proven."

# ── 0. toolchain ──────────────────────────────────────────────────────────────
beat "Toolchain" "rust + stellar-cli (the guest/proof are pre-built into fixtures)"
command -v cargo   >/dev/null || { echo "need rust/cargo"; exit 1; }
command -v stellar >/dev/null || { echo "need stellar-cli (cargo install --locked stellar-cli)"; exit 1; }
ok "cargo $(cargo --version | awk '{print $2}'),  stellar $(stellar --version 2>/dev/null | head -1 | awk '{print $2}')"

# ── 1. build the four generic contracts to wasm ───────────────────────────────
beat "Build the four production contracts → wasm" "factory · bond · vault · settlement (one generic vault + settlement, reused by every instrument)"
stellar contract build >/dev/null 2>&1
for w in factory bond vault settlement; do
  f="target/wasm32v1-none/release/parallar_${w}.wasm"
  [ -f "$f" ] && ok "$(printf '%-11s' "$w") $(wc -c < "$f" | tr -d ' ') bytes"
done

# ── 2. registry + factory: register a type, deploy TWO instruments ────────────
beat "Registry/Factory: register credit_v1, factory-deploy TWO instruments" \
     "one tx each; the second proves the family replicates on the same generic core"
run "deploy_instrument → cross-bound vault+settlement, pinned to the type image_id" \
    Cargo.toml parallar-factory deploy_instrument_creates_cross_bound_live_pair
run "second deploy is an independent instance (the replication beat)" \
    Cargo.toml parallar-factory second_deploy_is_an_independent_instance
run "factory refuses clawback/freezable collateral (asset-policy gate)" \
    Cargo.toml parallar-factory ineligible_collateral_rejected

# ── 3. vault: deposits + Poseidon-committed cover (positions hidden) ───────────
beat "Vault: seller deposits (public) + buyer cover as Poseidon commitments only" \
     "cover sizes never touch public state; only the opaque commitment + a public aggregate"
run "deposit / committed cover / solvency floor / settlement-only payouts" \
    Cargo.toml parallar-vault ""

# ── 3b. history-builder: the witness comes from observed chain data ───────────
beat "history-builder: assemble the witness from observed chain data (§10)" \
     "asset-received basis (classic ops + SAC transfers + path payments) · muxed→base account · clawback-aware"
run "qualifying-payment scan: address normalization + asset filter + clawback" \
    prover/Cargo.toml parallar-prover-host --lib history_builder

# ── 4. the guest determines the outcome — and REFUSES to prove a non-default ──
beat "Guest: a fully-paid epoch is UNPROVABLE — no settlement proof can exist" \
     "ZK is structural: if the trigger didn't occur, the guest panics on honest data"
run "fully_paid → NoDefault: the prover cannot produce a proof" \
    prover/Cargo.toml settle-credit-v1 fully_paid_is_unprovable
run "partial default → determination + pro-rata payout, soundness bindings" \
    prover/Cargo.toml settle-credit-v1 ""

# ── 5. the REAL proof, VERIFIED ON-CHAIN, paying out through the vault ─────────
beat "Settlement: a REAL Groth16 proof verifies ON-CHAIN and pays out" \
     "the committed fixture proof → the actual RISC Zero verifier (BN254+Poseidon host fns) → vault payout"
run "real Parallar proof verifies through the on-chain groth16-verifier" \
    prover/Cargo.toml parallar-prover-host --test onchain_verify real_parallar_proof_verifies_on_chain
run "FULL settle(): proof → bindings → confidential payout from the vault" \
    prover/Cargo.toml parallar-prover-host --test onchain_verify full_settlement_pays_out_with_real_proof
a=prover/host/tests/fixtures/real_proof.json
if [ -f "$a" ]; then
  note "proof artifact: seal=$(python3 -c "import json;print(len(json.load(open('$a'))['seal'])//2)" 2>/dev/null)B (selector 73c457ba), \
image_id=$(python3 -c "import json;print(json.load(open('$a'))['image_id'][:16])" 2>/dev/null)…, \
payout=$(python3 -c "import json;print(json.load(open('$a'))['total_payout'])" 2>/dev/null)"
fi

# ── 6. negative paths: nothing else can authorize a payout ────────────────────
beat "Negative paths revert — verification is the SOLE authorization" \
     "no admin, no pause-and-pay; a bad proof or a tampered binding cannot settle"
run "forged / tampered seal rejected on-chain" \
    prover/Cargo.toml parallar-prover-host --test onchain_verify tampered_seal_rejected_on_chain
run "forged proof reverts (settlement gate)"            Cargo.toml parallar-settlement forged_proof_reverts
run "replay (one settlement per epoch) reverts"         Cargo.toml parallar-settlement replay_same_epoch_reverts
run "stale position_root reverts"                       Cargo.toml parallar-settlement stale_position_root_reverts
run "tampered allocation_root reverts"                  Cargo.toml parallar-settlement tampered_allocation_root_reverts
run "settling before the deadline reverts"             Cargo.toml parallar-settlement settling_before_deadline_reverts

# ── 7. benchmarks ─────────────────────────────────────────────────────────────
beat "Benchmarks"
note "on-chain verify   ≈ 35M CPU insns  (Bn254Pairing 17.5M + G2-subgroup 11.8M + G1Mul 5.8M); ~3× headroom under ~100M/tx"
note "proof generation  ≈ 2027.77 s (N=1) on Apple-Silicon via Rosetta-x86 Docker (STARK + SNARK wrap); production proving on x86"
note "(N=10 + 1k-holder extrapolation: capture on an x86 VM — Rosetta is ~34 min/proof)"

printf "\n${bold}${grn}  ✓ Parallar demo complete — every beat ran against real code.${rst}\n"
printf "${dim}  Going live: prove a settlement and submit it to testnet with the host CLI:\n"
printf "    cargo run -p parallar-prover-host --bin parallar-prover -- prove  --inputs witness.json --out proof.json\n"
printf "    cargo run -p parallar-prover-host --bin parallar-prover -- submit --artifact proof.json --settlement <C…>\n"
printf "  Trust model + the path to a live pilot: README.md and docs/PRODUCTION_GAP.md${rst}\n\n"
