//! Generated by risc0-build at compile time, one pair per registered guest type:
//! `SETTLE_CREDIT_V1_GUEST_ELF` / `_ID` and `SETTLE_WEATHER_V1_GUEST_ELF` / `_ID` (instance #2).
//! Each `_ID` is the image_id an instrument's settlement contract is pinned to; the host proves
//! against the ELF and the contract verifies against the ID. A new guest = a new ELF/ID pair
//! here = a new registered type — never an in-place edit of an existing one (the versioning law).
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
