//! Generated by risc0-build at compile time, one ELF/ID pair per registered guest type: credit_v1
//! (deployed), credit_v2 (G1 attested), credit_v3 (G4 record-date), weather_v1 (instance #2),
//! claim_credit_v1 (G2 escape hatch), solvency_v1 (G3 confidential cover).
//! Each `_ID` is the image_id an instrument's settlement contract is pinned to; the host proves
//! against the ELF and the contract verifies against the ID. A new guest = a new ELF/ID pair
//! here = a new registered type — never an in-place edit of an existing one (the versioning law).
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
