//! Generated by risc0-build at compile time: `SETTLE_CREDIT_V1_GUEST_ELF` (the guest binary)
//! and `SETTLE_CREDIT_V1_GUEST_ID` (its image_id — what an instrument's settlement contract
//! is pinned to). The host proves against the ELF and the contract verifies against the ID.
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
