#!/usr/bin/env bash
#
# Independently verify Parallar's settlement from PUBLIC artifacts — no trust in us required.
# Decodes the committed real-proof journal, checks its self-consistency, cross-checks it against
# the deployed testnet record, and prints the exact commands to verify the proof ON-CHAIN and to
# reproduce the pinned guest image_id. See VERIFY.md for what each step proves.
set -euo pipefail
cd "$(dirname "$0")/.."

F="prover/host/tests/fixtures/real_proof.json"
D="deployments/testnet.json"
bold=$(tput bold 2>/dev/null || true); grn=$(tput setaf 2 2>/dev/null || true); rst=$(tput sgr0 2>/dev/null || true)

[ -f "$F" ] || { echo "missing $F (the committed real proof)"; exit 1; }

printf "${bold}── 1. decode the 116-byte journal + check it is self-consistent ──${rst}\n"
python3 - "$F" "$D" <<'PY'
import json, sys, hashlib
a = json.load(open(sys.argv[1]))
d = json.load(open(sys.argv[2]))
j = bytes.fromhex(a["journal"])
assert len(j) == 116, f"journal must be 116 bytes, got {len(j)}"
fields = {
    "instrument_id":   j[0:32].hex(),
    "epoch":           int.from_bytes(j[32:36], "big"),
    "deadline":        int.from_bytes(j[36:44], "big"),
    "position_root":   j[44:76].hex(),
    "allocation_root": j[76:108].hex(),
    "total_payout":    int.from_bytes(j[108:116], "big"),
}
for k, v in fields.items():
    print(f"    {k:<16} {v}")
# self-consistency: the contract recomputes sha256(journal); the verifier binds to it
dig = hashlib.sha256(j).hexdigest()
assert dig == a["journal_digest"], "journal_digest mismatch!"
print(f"  [ok] sha256(journal) == journal_digest ({dig[:16]}…)")
# the seal is the 260-byte selector-wrapped Groth16 proof the on-chain router expects
seal = bytes.fromhex(a["seal"])
assert len(seal) == 260 and seal[:4].hex() == "73c457ba", "seal must be 260B, selector 73c457ba"
print(f"  [ok] seal is 260 bytes, selector 73c457ba")
# the proof binds to the DEPLOYED type's pinned image_id (the versioning law: this demo proof
# was generated by the SAME pinned guest the live instruments use)
assert a["image_id"] == d["type"]["image_id"], "fixture image_id != deployed type image_id!"
print(f"  [ok] image_id == deployed type image_id ({a['image_id'][:16]}…)")
# this is the reproducible DEMO proof, for its own scenario instrument; the live on-chain
# settlement is a SEPARATE artifact (its own instrument + tx — see step 2).
print(f"  [ok] demo proof for instrument {fields['instrument_id'][:16]}…, total_payout {fields['total_payout']}")
settled = [i for i in d["instruments"] if i["settled"]]
if settled:
    print(f"  [note] the LIVE settled instrument is {settled[0]['instrument_id'][:16]}… (cover {settled[0]['cover']}); see its tx in step 2")
PY

printf "\n${bold}── 2. the live on-chain settlement (verify in a browser) ──${rst}\n"
python3 - "$D" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
ls = d["live_settlement"]
print(f"    settlement tx : {ls['explorer']}")
print(f"    factory       : https://stellar.expert/explorer/testnet/contract/{d['contracts']['factory']}")
print(f"    verifier      : https://stellar.expert/explorer/testnet/contract/{d['contracts']['groth16_verifier']}")
print(f"    expect events : transfer(vault->buyer) + Settled(epoch)")
PY

printf "\n${bold}── 3. verify the proof ON-CHAIN yourself (real verifier; no 34-min proof) ──${rst}\n"
echo "    cargo test -p parallar-prover-host --test onchain_verify"
echo "    (runs the committed proof through the deployed Groth16 verifier's logic in-process)"

printf "\n${bold}── 4. confirm there is NO mock-verify path (verification is the sole gate) ──${rst}\n"
if grep -rniE 'mock[-_]?verify' contracts/settlement/ >/dev/null 2>&1; then
  echo "    [FAIL] a mock-verify path exists"; exit 1
else
  printf "    ${grn}[ok]${rst} no mock-verify in the settlement contract\n"
fi

printf "\n${bold}── 5. reproduce the pinned image_id (needs the risc0 toolchain) ──${rst}\n"
echo "    cd prover && cargo build -p parallar-methods"
echo "    SETTLE_CREDIT_V1_GUEST_ID must hash to the deployed image_id (705ddac4…)."

printf "\n${bold}── 6. reproduce the determination + invariants (native, fast) ──${rst}\n"
echo "    cargo test                                   # the four contracts"
echo "    cd prover && cargo test -p settle-credit-v1 -p parallar-proptests"
echo "    cd prover && cargo test -p parallar-prover-host --test scale -- --ignored --nocapture"

printf "\n${grn}${bold}  Everything above is checkable from public data + this repo.${rst}\n"
printf "  What a proof guarantees: correct computation over the supplied inputs (TECH_SPEC §1).\n"
printf "  Input canonicity is gap G1 — a first cut (credit_v2, issuer-signed) is built.\n"
